@startuml
skinparam style strictuml
autonumber

actor "ATCC" as ATCC
participant ":System" as SYS

ATCC -> SYS : searchAircrafts(model, status, year)
activate SYS

SYS --> ATCC : returns list of aircrafts (200 OK)
deactivate SYS

@enduml