@startuml
title US202-CD

skinparam classAttributeIconSize 0

class AircraftModelController {
    + updateModelImage(modelName: String, dto: UpdateModelImageDTO): ResponseEntity<AircraftModelViewDTO>
}

class AircraftModelService {
    + updateModelImage(modelName: String, dto: UpdateModelImageDTO): AircraftModelViewDTO
}

interface AircraftModelRepository <<Repository>> {
    + findByModelName_Name(modelName: String): Optional<AircraftModel>
    + save(model: AircraftModel): AircraftModel
}

class AircraftModel <<Entity>> <<Root>> {
    - modelPhotoUrl: String
    + updateImage(newImageUrl: String)
}

class UpdateModelImageDTO <<DTO>> {
    + imageUrl: String
}

class AircraftModelViewDTO <<DTO>> {
    + modelName: String
    + modelPhotoUrl: String
    ...
}

AircraftModelController ..> UpdateModelImageDTO : consumes >
AircraftModelController ..> AircraftModelViewDTO : produces >
AircraftModelController --> AircraftModelService : uses >

AircraftModelService ..> UpdateModelImageDTO : uses >
AircraftModelService ..> AircraftModelViewDTO : creates >
AircraftModelService --> AircraftModelRepository : uses >
AircraftModelService --> AircraftModel : updates >

AircraftModelRepository --> AircraftModel : persists >
@enduml