@startuml
skinparam style strictuml
hide empty members

package "Aircraft Model Aggregate" {

    class AircraftModel <<Entity>> <<Root>> {
        - defaultSeatingCapacity : Integer
        - fuelCapacity : Double
        - maximumRange : Double
        - cruisingSpeed : Double
        - modelPhotoUrl : String
        - operatingHoursRange : String
        - seatingConfiguration : String
    }

    class ModelName <<Value Object>> {
        - name : String
    }

    enum Manufacturer <<Enum>> {
        AIRBUS
        BOEING
        EMBRAER
        BOMBARDIER
        ATR
    }

    AircraftModel *-- "1" ModelName : identifies <
    AircraftModel *-- "1" Manufacturer : produced by >
}

@enduml