@startuml
title US215-DM
hide methods

class Route {
    - String routeIdentifier
    - String originIataCode
    - String destinationIataCode
    - int minimumRange
    - int distance
    - String routeStatus
}
@enduml