@startuml
title US207-SD
autonumber
actor "Backoffice Operator" as Operator
participant ":AirportController" as Ctrl
participant "dto\n:UpdateAirportImageDTO" as DTO
participant ":AirportService" as Service
participant ":AirportRepository" as Repo
participant "airport\n:Airport" as Entity

activate Operator
Operator -> Ctrl : PATCH /api/airports/{iataCode}/image\n(UpdateAirportImageDTO)
activate Ctrl

Ctrl -> DTO : imageUrl()
activate DTO
DTO --> Ctrl : imageUrl
deactivate DTO

Ctrl -> Service : updateAirportImage(iataCode, imageUrl)
activate Service

Service -> Repo : findByIataCodeString(iataCode)
activate Repo
Repo --> Service : Optional<Airport>
deactivate Repo

Service -> Entity : updateImage(imageUrl)
activate Entity
Entity --> Service : success
deactivate Entity

Service -> Repo : save(airport)
activate Repo
Repo --> Service : savedAirport
deactivate Repo

Service -> Service : create AirportViewDTO
Service --> Ctrl : AirportViewDTO
deactivate Service

Ctrl -> Ctrl : wrap in EntityModel & add HATEOAS self link
Ctrl --> Operator : 200 OK (EntityModel<AirportViewDTO>)
deactivate Ctrl
deactivate Operator
@enduml