@startuml
title US212 - SSD
autonumber
actor "Air Traffic Control Coordinator" as ATCC
participant ":AISafeSystem" as System

ATCC -> System : assignAircraftToRoute(String routeIdentifier, String registrationNumber, LocalDateTime scheduledDateTime)
activate System
System --> ATCC : 201 Created (ScheduledFlightDataTransferObject)
deactivate System
@enduml