@startuml
title US212 - DM
hide methods

class ScheduledFlight {
    - String registrationNumber
    - String routeIdentifier
    - LocalDateTime scheduledDateTime
    - String flightStatus
}

class Aircraft {
    - String registrationNumber
    - String aircraftStatus
    - int actualSeatingCapacity
}

class Route {
    - String routeIdentifier
    - String originIataCode
    - String destinationIataCode
    - int minimumRange
}

class AircraftModel {
    - String modelName
    - double maximumRange
}

ScheduledFlight "1" -- "1" Aircraft : assignedTo
ScheduledFlight "1" -- "1" Route : follows
Aircraft "1" -- "1" AircraftModel : hasModel
@enduml