@startuml
title US212 - SD
autonumber
participant "AircraftController" as AircraftController
participant "AircraftService" as AircraftService
participant "RouteRepository" as RouteRepository
participant "AircraftRepository" as AircraftRepository
participant "ScheduledFlightRepository" as ScheduledFlightRepository
participant "ScheduledFlight" as ScheduledFlightDomain

AircraftController -> AircraftService : assignAircraft(String routeIdentifier, String registrationNumber, LocalDateTime scheduledDateTime)
activate AircraftService

AircraftService -> RouteRepository : findById(String routeIdentifier)
activate RouteRepository
RouteRepository -->> AircraftService : Route route
deactivate RouteRepository

AircraftService -> AircraftRepository : findByRegistrationNumber(String registrationNumber)
activate AircraftRepository
AircraftRepository -->> AircraftService : Aircraft aircraft
deactivate AircraftRepository

AircraftService -> ScheduledFlightRepository : findByAircraft_RegistrationNumber(String registrationNumber)
activate ScheduledFlightRepository
ScheduledFlightRepository -->> AircraftService : List<ScheduledFlight> flightList
deactivate ScheduledFlightRepository

AircraftService -> AircraftService : validateConstraints(Route route, Aircraft aircraft, List<ScheduledFlight> flightList)
activate AircraftService
AircraftService -->> AircraftService : boolean valid
deactivate AircraftService

create ScheduledFlightDomain
AircraftService -> ScheduledFlightDomain : new ScheduledFlight(routeIdentifier, registrationNumber, scheduledDateTime)
ScheduledFlightDomain -->> AircraftService : ScheduledFlight scheduledFlight

AircraftService -> ScheduledFlightRepository : save(ScheduledFlight scheduledFlight)
activate ScheduledFlightRepository
ScheduledFlightRepository -->> AircraftService : ScheduledFlight savedScheduledFlight
deactivate ScheduledFlightRepository

AircraftService -->> AircraftController : ScheduledFlightDataTransferObject flightDataTransferObject
deactivate AircraftService
@enduml