@startuml
skinparam style strictuml
autonumber

actor "ATCC" as ATCC
participant ":System" as SYS

ATCC -> SYS : updateAircraftStatus(registrationNumber, newStatus)
activate SYS

SYS --> ATCC : informs operation success and returns updated details (200 OK)
deactivate SYS

@enduml