@startuml
skinparam style strictuml
autonumber

actor "ATCC" as ATCC
participant ":System" as SYS

ATCC -> SYS : getAircraftDetails(registrationNumber)
activate SYS

SYS --> ATCC : returns aircraft details (200 OK)
deactivate SYS

@enduml