@startuml
skinparam style strictuml
autonumber

actor "ATCC" as ATCC
participant "AircraftController" as CTRL
participant "AircraftService" as SVC
participant "ModelName" as MN <<Value Object>>
participant "AircraftModelRepository" as MREPO
participant "RegistrationNumber" as RN <<Value Object>>
participant "Aircraft" as ENT <<Entity>>
participant "AircraftRepository" as AREPO

ATCC -> CTRL : POST /api/aircraft-models/instances (RegisterAircraftDTO)
activate CTRL

CTRL -> SVC : registerAircraft(dto)
activate SVC

' 1. Procurar o modelo base
SVC -> MN ** : create(dto.modelName())
SVC -> MREPO : findByModelName(modelName)
activate MREPO
MREPO --> SVC : aircraftModel
deactivate MREPO

' 2. Criar a nova instância
SVC -> RN ** : create(dto.registrationNumber())
SVC -> ENT ** : create(registrationNumber, aircraftModel, \ndto.manufacturingDate(), dto.seatingCapacity())
activate ENT
note right of ENT
  Constructor validates inputs and sets
  initial status to ACTIVE and
  totalFlightHours to 0.0
end note
ENT --> SVC : aircraft
deactivate ENT

' 3. Persistir e devolver
SVC -> AREPO : save(aircraft)
activate AREPO
AREPO --> SVC : savedAircraft
deactivate AREPO

SVC --> CTRL : void
deactivate SVC

CTRL -> CTRL : add(linkTo(self).withSelfRel())

CTRL --> ATCC : 201 Created (EntityModel<DTO> with HATEOAS)
deactivate CTRL

@enduml