@startuml
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
title AISafe Domain Model
hide empty members

package "Aircraft Model Aggregate" {
    class AircraftModel <<Entity>> <<Root>> {
        - manufacturer: String
        - defaultSeatingCapacity: Integer
        - fuelCapacity: Double
        - maximumRange: Double
        - cruisingSpeed: Double
        - imageOrDiagram: String
        - operatingHoursRange: String
        - seatingConfiguration: String
    }
    class ModelName <<Value Object>> {
        - name: String
    }
    AircraftModel "1" *-- "1" ModelName : identified by >
}

package "Aircraft Aggregate" {
    class Aircraft <<Entity>> <<Root>> {
        - manufacturingDate: Date
        - actualSeatingCapacity: Integer
        - totalFlightHours: Double
        - operatingHoursRange: String
        - seatingConfiguration: String
    }
    class RegistrationNumber <<Value Object>> {
        - number: String
    }
    class AircraftStatus <<Value Object>> {
        ACTIVE
        INACTIVE
        UNDER_MAINTENANCE
         'US102
    }
    class AircraftFeature <<Value Object>> {
        - description: String
        ' e.g., WiFi-enabled, specific engine type
    }

    Aircraft "1" *-- "1" RegistrationNumber : identified by >
    Aircraft "1" *-- "1" AircraftStatus : has >
    Aircraft "1" *-- "*" AircraftFeature : has >
    Aircraft "*" --> "1" AircraftModel : is of type >
}

package "Airport Aggregate" {
    class Airport <<Entity>> <<Root>> {
        - name: String
        - city: String
        - country: String
        - region: String
        - timezone: String
        - operationalHours: String
    }

    class AirportType <<Value Object>> {
            INTERNATIONAL
            REGIONAL
            DOMESTIC
        }

    class IATACode <<Value Object>> {
        - code: String
    }
    class AirportStatus <<Value Object>> {
        OPERATIONAL
        CLOSED
        UNDER_MAINTENANCE
        'US109
    }
    class Coordinates <<Value Object>> {
        - latitude: Double
        - longitude: Double
    }
    class Runway <<Entity>> {
        - name: String
        - length: Double
        - orientation: String
    }
    class Contact <<Value Object>> {
        - type: String
        - value: String
        - description: String
    }
    class Facility <<Value Object>> {
        - type: String
        - description: String
    }

    class AirplaneCertification <<Entity>> {
            - issueDate: Date
            - expiryDate: Date
            - certificationNumber: String
        }

    Airport "1" *-- "1" IATACode : identified by >
    Airport "1" *-- "1" Coordinates : located at >
    Airport "1" *-- "1" AirportStatus : has >
    Airport "1" *-- "*" Runway : contains >
    Airport "1" *-- "*" Contact : has >
    Airport "1" *-- "*" Facility : has >
    Airport "1" *-- "*" AirplaneCertification : issues >
    AirplaneCertification "*" --> "1" AircraftModel : authorizes >
    Airport "1" *-- "1" AirportType : is of type >
}

package "Route Aggregate" {
    class Route <<Entity>> <<Root>> {
        - estimatedFlightTime: Integer
        - minimumRange: Double
        - minimumCapacity: Integer
        - distance: Double

    }

    class RouteHistory <<Value Object>> {
            - startDate: Date
            - endDate: Date
        }

    class RouteId <<Value Object>> {
        - id: String

    }
    class RouteStatus <<Value Object>> {
      ACTIVE
      INACTIVE
        'US112
    }

    Route "1" *-- "1" RouteId : identified by >
    Route "1" *-- "1" RouteStatus : has >
    Route "*" --> "1" Airport : departs from (Origin) >
    Route "*" --> "1" Airport : arrives at (Destination) >
    Route "1" *-- "1" RouteHistory : has >
}


package "Flight Operations Aggregate" {
    class ScheduledFlight <<Entity>> <<Root>> {
        - scheduledDateTime: DateTime
        - scheduledArrivalDateTime: DateTime
        - actualDepartureDateTime: DateTime
        - actualArrivalDateTime: DateTime
    }
    class FlightStatus <<Value Object>> {
       SCHEDULED
       DELAYED
       IN_FLIGHT
       COMPLETED
       CANCELED
       'forum-pergunta sobre US212
    }

    ScheduledFlight "1" *-- "1" FlightStatus : has >
    ScheduledFlight "*" --> "1" Route : operates on >
    ScheduledFlight "*" --> "1" Aircraft : assigned to >
}


package "Maintenance Template Aggregate" {
    class MaintenanceTemplate <<Entity>> <<Root>> {
        - templateName: String
        - templateType: String
        - flightHoursInterval: Double
        - calendarDaysInterval: Integer

    }
    class ChecklistItem <<Value Object>> {
        - description: String
    }

    MaintenanceTemplate "1" *-- "*" ChecklistItem : contains >
    MaintenanceTemplate "*" --> "*" AircraftModel : applies to >
}


package "Maintenance Record Aggregate" {
    class MaintenanceRecord <<Entity>> <<Root>> {
        - description: String
        - startDate: Date
        - expectedDuration: Integer
        - completionNotes: String
        - componentCategory: String

        - cost: Double
    }
    class MaintenanceRecordStatus <<Value Object>> {
    SCHEDULED
    IN_PROGRESS
     COMPLETED
     'US115 e US119

    }

    MaintenanceRecord "1" *-- "1" MaintenanceRecordStatus : has >
    MaintenanceRecord "*" --> "1" Aircraft : performed on >
    MaintenanceRecord "*" --> "1" MaintenanceTemplate : follows >
}


package "Inventory Aggregate" {
    class MaintenancePart <<Entity>> <<Root>> {
        - name: String
        - description: String
        - stockQuantity: Integer
        - minimumThreshold: Integer

    }
    class PartNumber <<Value Object>> {
        - number: String
    }

    MaintenancePart "1" *-- "1" PartNumber : identified by >

}

@enduml