@startuml
skinparam style strictuml
skinparam packageStyle rectangle

title Class Diagram - US111

package "Application Layer" {
    class RouteService {
        + updateRouteStatus(id: String, status: String): void
    }
}

package "Domain Layer" {
    class Route <<Entity>> <<Root>> {
        + deactivate(): void
    }

    class RouteHistory <<Value Object>> {
        - startDate: Date
        - endDate: Date
        + closeHistory(endDate: Date): void
    }
}

RouteService .down.> Route : updates
Route *-- "1" RouteHistory

@enduml